"""Database with one teacher

Revision ID: 0bfe486bc65a
Revises: 
Create Date: 2025-02-25 19:23:46.458354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfe486bc65a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupes',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', 'level', name='uq_numero_level')
    )
    op.create_table('modules',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('coef', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('module_code', sa.String(length=10), nullable=False),
    sa.Column('type_quizz', sa.String(length=2), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=6), nullable=False),
    sa.Column('groupe', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['groupe'], ['groupes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'quiz_id', name='uq_qstn_id_quizz')
    )
    op.create_table('quiz_groupe',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groupes.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'group_id')
    )
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'question_id', name='uq_answ_id_qstn')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=7), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('quizz_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_results_student_id'), 'results', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_student_id'), table_name='results')
    op.drop_table('results')
    op.drop_table('choices')
    op.drop_table('quiz_groupe')
    op.drop_table('questions')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_table('modules')
    op.drop_table('groupes')
    # ### end Alembic commands ###
