"""update1

Revision ID: 51ebce1b8bc3
Revises: 
Create Date: 2025-02-26 16:18:01.067333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51ebce1b8bc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id_reclamation', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.String(length=9), nullable=False),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('statut', sa.Boolean(), nullable=False),
    sa.Column('date_reclamation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_quiz'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id_reclamation')
    )
    op.create_table('quiz_groupe',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groupes.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'group_id')
    )
    op.create_table('statistiques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_student', sa.String(length=9), nullable=False),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_quiz'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'question_id', name='uq_answ_id_qstn')
    )
    op.drop_table('answer_result')
    op.drop_index('uq_answ_id_qstn', table_name='answers')
    op.drop_table('answers')
    op.drop_table('teacher_module')
    op.drop_table('teacher_groupe')
    op.drop_table('quizz_groupe')
    op.drop_index('ix_teachers_email', table_name='teachers')
    op.drop_index('ix_teachers_id', table_name='teachers')
    op.drop_table('teachers')
    op.alter_column('groupes', 'level',
               existing_type=mysql.VARCHAR(length=4),
               type_=sa.String(length=6),
               existing_nullable=False)
    op.alter_column('modules', 'level',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=6),
               existing_nullable=False)
    op.add_column('questions', sa.Column('quiz_id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('statement', sa.Text(), nullable=False))
    op.drop_constraint('uq_qstn_id_quizz', 'questions', type_='unique')
    op.create_unique_constraint('uq_qstn_id_quizz', 'questions', ['id', 'quiz_id'])
    op.drop_constraint('questions_ibfk_1', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('questions', 'quizz_id')
    op.drop_column('questions', 'qstn')
    op.alter_column('quizzes', 'type_quizz',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.add_column('results', sa.Column('choice_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'results', 'choices', ['choice_id'], ['id'])
    op.add_column('students', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('groupe', sa.String(length=8), nullable=False))
    op.alter_column('students', 'level',
               existing_type=mysql.VARCHAR(length=4),
               type_=sa.String(length=6),
               existing_nullable=False)
    op.drop_constraint('students_ibfk_1', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'groupes', ['groupe'], ['id'])
    op.drop_column('students', 'lname')
    op.drop_column('students', 'fname')
    op.drop_column('students', 'groupe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('groupe_id', mysql.VARCHAR(length=6), nullable=False))
    op.add_column('students', sa.Column('fname', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('students', sa.Column('lname', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_ibfk_1', 'students', 'groupes', ['groupe_id'], ['id'])
    op.alter_column('students', 'level',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=4),
               existing_nullable=False)
    op.drop_column('students', 'groupe')
    op.drop_column('students', 'name')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'choice_id')
    op.alter_column('quizzes', 'type_quizz',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=False)
    op.add_column('questions', sa.Column('qstn', mysql.TEXT(), nullable=False))
    op.add_column('questions', sa.Column('quizz_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_ibfk_1', 'questions', 'quizzes', ['quizz_id'], ['id'])
    op.drop_constraint('uq_qstn_id_quizz', 'questions', type_='unique')
    op.create_unique_constraint('uq_qstn_id_quizz', 'questions', ['id', 'quizz_id'])
    op.drop_column('questions', 'statement')
    op.drop_column('questions', 'quiz_id')
    op.alter_column('modules', 'level',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('groupes', 'level',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=4),
               existing_nullable=False)
    op.create_table('teachers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_teachers_id', 'teachers', ['id'], unique=False)
    op.create_index('ix_teachers_email', 'teachers', ['email'], unique=True)
    op.create_table('quizz_groupe',
    sa.Column('quizz_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groupes.id'], name='quizz_groupe_ibfk_1'),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], name='quizz_groupe_ibfk_2'),
    sa.PrimaryKeyConstraint('quizz_id', 'group_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher_groupe',
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groupes.id'], name='teacher_groupe_ibfk_1'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teacher_groupe_ibfk_2'),
    sa.PrimaryKeyConstraint('teacher_id', 'group_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher_module',
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_code', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], name='teacher_module_ibfk_1'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teacher_module_ibfk_2'),
    sa.PrimaryKeyConstraint('teacher_id', 'module_code'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('answers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quizz_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_ibfk_1'),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], name='answers_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_answ_id_qstn', 'answers', ['id', 'question_id'], unique=True)
    op.create_table('answer_result',
    sa.Column('answer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name='answer_result_ibfk_1'),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name='answer_result_ibfk_2'),
    sa.PrimaryKeyConstraint('answer_id', 'result_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('choices')
    op.drop_table('statistiques')
    op.drop_table('quiz_groupe')
    op.drop_table('complaints')
    # ### end Alembic commands ###
